parameters:
  zed:
    x: 2.777
    y: 0.932
    z: 3.000
    r: 5.920
    p: 3.440
    y: 1.000
  lane_detection:
    low: 245.952
    high: 188.371
    z: 0.821
    min_pts: 0.243
    eps: 0.615
limits:
  zed:
    x:
      min: 0.000
      max: 3.000
    y:
      min: 0.000
      max: 3.000
    z:
      min: 0.000
      max: 3.000
    r:
      min: 0.000
      max: 6.283
    p:
      min: 0.000
      max: 6.283
    y:
      min: 0.000
      max: 6.283
  lane_detection:
    low:
      min: 0.000
      max: 255.000
    high:
      min: 0.000
      max: 255.000
    z:
      min: 0.000
      max: 1.000
    min_pts:
      min: 0.000
      max: 1.000
    eps:
      min: 0.000
      max: 1.000