parameters:
  zed:
    x: 1.743
    y: 1.449
    z: 1.541
    r: 4.330
    p: 4.245
    y: 1.000
  lane_detection:
    low: 122.565
    high: 148.065
    z: 0.513
    min_pts: 0.497
    eps: 0.174
limits:
  zed:
    x:
      min: 0.000
      max: 3.000
    y:
      min: 0.000
      max: 3.000
    z:
      min: 0.000
      max: 3.000
    r:
      min: 0.000
      max: 6.283
    p:
      min: 0.000
      max: 6.283
    y:
      min: 0.000
      max: 6.283
  lane_detection:
    low:
      min: 0.000
      max: 255.000
    high:
      min: 0.000
      max: 255.000
    z:
      min: 0.000
      max: 1.000
    min_pts:
      min: 0.000
      max: 1.000
    eps:
      min: 0.000
      max: 1.000